"""drop user_season table

Revision ID: 1ad438a71e55
Revises: baa6a50ace52
Create Date: 2025-08-11 20:00:59.652545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad438a71e55'
down_revision: Union[str, None] = 'baa6a50ace52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_season')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_season',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('season_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name=op.f('user_season_season_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'guild_id', 'season_id', name=op.f('user_season_pkey'))
    )
    # ### end Alembic commands ###
