"""added seasons, achievements

Revision ID: 6e574cdf96e2
Revises: 2c761462d33e
Create Date: 2025-06-02 04:22:23.941909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e574cdf96e2'
down_revision: Union[str, None] = '2c761462d33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('saved_nicknames', sa.Integer(), nullable=True))
    op.add_column('user_stats', sa.Column('coins', sa.Integer(), nullable=True))
    op.add_column('user_stats', sa.Column('coins_earned', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_stats', 'saved_nicknames', ['saved_nicknames'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stats', type_='foreignkey')
    op.drop_column('user_stats', 'coins_earned')
    op.drop_column('user_stats', 'coins')
    op.drop_column('user_stats', 'saved_nicknames')
    # ### end Alembic commands ###
