"""added is_current is season table

Revision ID: baa6a50ace52
Revises: 6e574cdf96e2
Create Date: 2025-08-11 19:58:30.576540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baa6a50ace52'
down_revision: Union[str, None] = '6e574cdf96e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('is_current', sa.Boolean(), nullable=False))
    op.alter_column('season', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('user_season_stats_user_id_guild_id_season_id_fkey'), 'user_season_stats', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_season_stats_user_id_guild_id_season_id_fkey'), 'user_season_stats', 'user_season', ['user_id', 'guild_id', 'season_id'], ['user_id', 'guild_id', 'season_id'])
    op.alter_column('season', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('season', 'is_current')
    # ### end Alembic commands ###
