"""added roll bonuses in user_stats_dev

Revision ID: be20836a2027
Revises: 70256e971bdc
Create Date: 2025-08-14 20:09:44.658246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be20836a2027'
down_revision: Union[str, None] = '70256e971bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats_dev', sa.Column('rolls_since_rare', sa.Integer(), nullable=True))
    op.add_column('user_stats_dev', sa.Column('roll_bonus_add', sa.Float(), nullable=True))
    op.add_column('user_stats_dev', sa.Column('roll_attempts_factor', sa.Float(), nullable=True))
    op.add_column('user_stats_dev', sa.Column('roll_base_attempts', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('user_stats_dev_user_id_guild_id_key'), 'user_stats_dev', type_='unique')
    op.drop_column('user_stats_dev', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats_dev', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('user_stats_dev_user_id_guild_id_key'), 'user_stats_dev', ['user_id', 'guild_id'])
    op.drop_column('user_stats_dev', 'roll_base_attempts')
    op.drop_column('user_stats_dev', 'roll_attempts_factor')
    op.drop_column('user_stats_dev', 'roll_bonus_add')
    op.drop_column('user_stats_dev', 'rolls_since_rare')
    # ### end Alembic commands ###
