"""added cascade delete to achievements and user_stats

Revision ID: c93fca132b06
Revises: be20836a2027
Create Date: 2025-08-14 21:27:59.390488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93fca132b06'
down_revision: Union[str, None] = 'be20836a2027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_achievement_achievement_id_fkey'), 'user_achievement', type_='foreignkey')
    op.create_foreign_key(None, 'user_achievement', 'achievement', ['achievement_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_achievement_stats_user_id_guild_id_fkey'), 'user_achievement_stats', type_='foreignkey')
    op.create_foreign_key(None, 'user_achievement_stats', 'user_stats', ['user_id', 'guild_id'], ['user_id', 'guild_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_stats_saved_nicknames_fkey'), 'user_stats', type_='foreignkey')
    op.create_foreign_key(None, 'user_stats', 'saved_nicknames', ['saved_nicknames'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_stats_dev_user_id_guild_id_fkey'), 'user_stats_dev', type_='foreignkey')
    op.create_foreign_key(None, 'user_stats_dev', 'user_stats', ['user_id', 'guild_id'], ['user_id', 'guild_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stats_dev', type_='foreignkey')
    op.create_foreign_key(op.f('user_stats_dev_user_id_guild_id_fkey'), 'user_stats_dev', 'user_stats', ['user_id', 'guild_id'], ['user_id', 'guild_id'])
    op.drop_constraint(None, 'user_stats', type_='foreignkey')
    op.create_foreign_key(op.f('user_stats_saved_nicknames_fkey'), 'user_stats', 'saved_nicknames', ['saved_nicknames'], ['id'])
    op.drop_constraint(None, 'user_achievement_stats', type_='foreignkey')
    op.create_foreign_key(op.f('user_achievement_stats_user_id_guild_id_fkey'), 'user_achievement_stats', 'user_stats', ['user_id', 'guild_id'], ['user_id', 'guild_id'])
    op.drop_constraint(None, 'user_achievement', type_='foreignkey')
    op.create_foreign_key(op.f('user_achievement_achievement_id_fkey'), 'user_achievement', 'achievement', ['achievement_id'], ['id'])
    # ### end Alembic commands ###
