"""added upgrade chance in user_stats_dev

Revision ID: dbec4d5af0c6
Revises: c93fca132b06
Create Date: 2025-08-15 03:08:16.239188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbec4d5af0c6'
down_revision: Union[str, None] = 'c93fca132b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'achievement', ['name'])
    op.add_column('user_stats_dev', sa.Column('roll_upgrade_chance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats_dev', 'roll_upgrade_chance')
    op.drop_constraint(None, 'achievement', type_='unique')
    # ### end Alembic commands ###
